# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: John Paul Newman
email:
description: > # this means to ignore newlines until 'baseurl:'
  Devops Engineer
baseurl: '' # the subpath of your site, e.g. /blog

include:
  - '.htaccess'
  - '*.md'

exclude:
  - 'Gemfile*'
  - 'Makefile'

url: 'http://johnpaulnewman.com' # the base hostname & protocol for your site
twitter_username:
github_username:  jpnewman

encoding:     'utf-8'

tag_title_prefix: ''
tag_title_suffix: ''

# Build settings
plugins:
- jekyll-assets

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

highlighter: pygments

markdown_ext: 'markdown,mkdown,mkdn,mkd,md'

relative_permalinks: false

pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage: 'index'

tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

category_dir: cat

kramdown:
  default_lang: php

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  input: GFM # GitHub Flavored Markdown
  linenos: table
  lineanchors: yes

sass:
  style: compressed

  compress:
    css: false # | true | default - development: false, production: true
    js: false # | true | default - development: false, production: true
  cache: false # | directory | default: .asset-cache
  # cdn: https://cdn.example.com
  skip_baseurl_with_cdn: false
  skip_prefix_with_cdn: false
  prefix: "/assets"
  autowrite: true
  assets:
    - "*.png"
    - "bundle.css"
  digest: false
  sources:
    - _assets/css
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/fonts
    - _assets/img
    - _assets/js
    - _assets/photos
  features:
    liquid: true # | false | default: false
    automatic_img_size: true # | false | n(fixnum): 2,4,6,8 | default: true
    automatic_img_alt : true # | false | default: true

# Jekyll-Photo-Gallery Settings
exiftag:
 sources:
   - images/photography/dublin
   - images/photography/london
   - images/photography/munich

photo_gallery:
  auto_discovery: true

# MiniMagick
# https://github.com/zroger/jekyll-minimagick
mini_magick:
    photography_dublin:
        source: images/photography/dublin
        destination: images/photography/dublin/thumbnails
        resize: "1280x720"
    photography_london:
        source: images/photography/london
        destination: images/photography/london/thumbnails
        resize: "1280x720"
    photography_munich:
        source: images/photography/munich
        destination: images/photography/munich/thumbnails
        resize: "1280x720"
    headers:
        source: images/headers
        destination: images/headers/thumbnails
        resize: "400x250"
